package server;


/**
* server/abonneOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* mercredi 24 janvier 2018 07 h 20 WET
*/

public interface abonneOperations 
{
  int numero ();
  String nom_prenom ();
} // interface abonneOperations
