package server;


/**
* server/gestionabonnesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* mercredi 24 janvier 2018 07 h 20 WET
*/

public interface gestionabonnesOperations 
{
  void creation_abonne (int numero, String nom, String prenom, server.abonneHolder ref) throws server.dejaExistant;
  void resilier_abonne (int numero) throws server.numeroInconnu;
  void rechercher_abonne (int numero, server.abonneHolder ref) throws server.numeroInconnu;
} // interface gestionabonnesOperations
