package server;


/**
* server/numeroInconnu.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* mercredi 24 janvier 2018 07 h 20 WET
*/

public final class numeroInconnu extends org.omg.CORBA.UserException
{

  public numeroInconnu ()
  {
    super(numeroInconnuHelper.id());
  } // ctor


  public numeroInconnu (String $reason)
  {
    super(numeroInconnuHelper.id() + "  " + $reason);
  } // ctor

} // class numeroInconnu
