package CosNaming;


/**
* CosNaming/etudiantPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNaming.idl
* lundi 12 février 2018 07 h 55 WET
*/

public abstract class etudiantPOA extends org.omg.PortableServer.Servant
 implements CosNaming.etudiantOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_nom", new java.lang.Integer (0));
    _methods.put ("_get_prenom", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CosNaming/etudiant/_get_nom
       {
         String $result = null;
         $result = this.nom ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // CosNaming/etudiant/_get_prenom
       {
         String $result = null;
         $result = this.prenom ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CosNaming/etudiant:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public etudiant _this() 
  {
    return etudiantHelper.narrow(
    super._this_object());
  }

  public etudiant _this(org.omg.CORBA.ORB orb) 
  {
    return etudiantHelper.narrow(
    super._this_object(orb));
  }


} // class etudiantPOA
