package CosNaming;


/**
* CosNaming/etudiant.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNaming.idl
* lundi 12 février 2018 07 h 55 WET
*/

public interface etudiant extends etudiantOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface etudiant
