package CosNaming;


/**
* CosNaming/etudiantOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CosNaming.idl
* lundi 12 février 2018 07 h 55 WET
*/

public interface etudiantOperations 
{
  String nom ();
  String prenom ();
} // interface etudiantOperations
