/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MVC;

import java.util.ArrayList;
import javax.swing.ListModel;

/**
 * Représente la vue principale de l'application. Affiche la liste des notes,
 * les statistiques calculées et la visualisation graphique
 *
 * @author riviere
 */
public class Ihm extends javax.swing.JPanel implements StatsListener {

    private final Controler controler;

    /**
     * Creates new form Ihm
     * @param c
     */
    public Ihm(Controler c) {
        initComponents();
        controler = c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setLayout(null);
        add(jSeparator1);
        jSeparator1.setBounds(0, 230, 618, 2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Visualisation Graphique");
        add(jLabel1);
        jLabel1.setBounds(210, 230, 170, 20);

        jList1.setEnabled(false);
        jScrollPane1.setViewportView(jList1);

        add(jScrollPane1);
        jScrollPane1.setBounds(70, 40, 70, 130);

        jButton1.setText("Sauvegarder résultats");
        add(jButton1);
        jButton1.setBounds(440, 190, 170, 23);

        jButton2.setText("Calculer statistiques");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(150, 90, 170, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Médiane :");
        add(jLabel3);
        jLabel3.setBounds(340, 110, 80, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Notes");
        add(jLabel4);
        jLabel4.setBounds(90, 20, 40, 14);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Moyenne :");
        add(jLabel5);
        jLabel5.setBounds(340, 60, 80, 14);

        jTextField1.setEnabled(false);
        add(jTextField1);
        jTextField1.setBounds(400, 110, 110, 20);

        jTextField2.setEnabled(false);
        add(jTextField2);
        jTextField2.setBounds(400, 60, 110, 20);

        jButton3.setText("Modifier Notes");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(40, 180, 120, 23);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Ouvre l'éditeur de notes NotesEditor et récupère la liste des notes
     * @param evt 
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       controler.editerNotes();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        controler.modifierNotes();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void statsUpdated(Double moyenne, Double mediane) {
        jTextField2.setText(moyenne.toString());
        jTextField1.setText(mediane.toString());
    }
    
    public void setNotesInList(Object[] notes){
        jList1.setListData(notes);
    }
    
    public ListModel<Object> getListModel(){
        return jList1.getModel();
    }
}
