package server;


/**
* server/bibliothequeOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* mercredi 31 janvier 2018 15 h 05 WET
*/

public interface bibliothequeOperations 
{
  server.ouvrage[] tous_les_ouvrages ();
  server.ouvrage ajouter_ouvrage (String titre) throws server.deja_trouve;
  void rechercher_ouvrage (server.liste_ouvrageHolder l, String mot) throws server.non_trouve;
} // interface bibliothequeOperations
