package server;


/**
* server/bibliothequeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* mercredi 31 janvier 2018 15 h 05 WET
*/

abstract public class bibliothequeHelper
{
  private static String  _id = "IDL:server/bibliotheque:1.0";

  public static void insert (org.omg.CORBA.Any a, server.bibliotheque that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static server.bibliotheque extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (server.bibliothequeHelper.id (), "bibliotheque");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static server.bibliotheque read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_bibliothequeStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, server.bibliotheque value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static server.bibliotheque narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof server.bibliotheque)
      return (server.bibliotheque)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      server._bibliothequeStub stub = new server._bibliothequeStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static server.bibliotheque unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof server.bibliotheque)
      return (server.bibliotheque)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      server._bibliothequeStub stub = new server._bibliothequeStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
