package server;


/**
* server/familleHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* mercredi 31 janvier 2018 15 h 05 WET
*/

abstract public class familleHelper
{
  private static String  _id = "IDL:server/famille:1.0";

  public static void insert (org.omg.CORBA.Any a, server.famille that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static server.famille extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (server.familleHelper.id (), "famille", new String[] { "revue", "livre", "bd", "cd", "dvd"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static server.famille read (org.omg.CORBA.portable.InputStream istream)
  {
    return server.famille.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, server.famille value)
  {
    ostream.write_long (value.value ());
  }

}
