package server;

/**
* server/non_trouveHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* mercredi 31 janvier 2018 15 h 05 WET
*/

public final class non_trouveHolder implements org.omg.CORBA.portable.Streamable
{
  public server.non_trouve value = null;

  public non_trouveHolder ()
  {
  }

  public non_trouveHolder (server.non_trouve initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = server.non_trouveHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    server.non_trouveHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return server.non_trouveHelper.type ();
  }

}
