package server;


/**
* server/ouvrageOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* mercredi 31 janvier 2018 15 h 05 WET
*/

public interface ouvrageOperations 
{
  String titre ();
  String auteurs ();
  void auteurs (String newAuteurs);
  String[] mots_clefs ();
  void mots_clefs (String[] newMots_clefs);
  server.famille famille_ouvrage ();
  void famille_ouvrage (server.famille newFamille_ouvrage);
} // interface ouvrageOperations
