package server;

/**
* server/ouvrageHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* mercredi 31 janvier 2018 15 h 05 WET
*/

public final class ouvrageHolder implements org.omg.CORBA.portable.Streamable
{
  public server.ouvrage value = null;

  public ouvrageHolder ()
  {
  }

  public ouvrageHolder (server.ouvrage initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = server.ouvrageHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    server.ouvrageHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return server.ouvrageHelper.type ();
  }

}
