package server;


/**
* server/ouvragePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* mercredi 31 janvier 2018 15 h 05 WET
*/

public abstract class ouvragePOA extends org.omg.PortableServer.Servant
 implements server.ouvrageOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_titre", new java.lang.Integer (0));
    _methods.put ("_get_auteurs", new java.lang.Integer (1));
    _methods.put ("_set_auteurs", new java.lang.Integer (2));
    _methods.put ("_get_mots_clefs", new java.lang.Integer (3));
    _methods.put ("_set_mots_clefs", new java.lang.Integer (4));
    _methods.put ("_get_famille_ouvrage", new java.lang.Integer (5));
    _methods.put ("_set_famille_ouvrage", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // server/ouvrage/_get_titre
       {
         String $result = null;
         $result = this.titre ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // server/ouvrage/_get_auteurs
       {
         String $result = null;
         $result = this.auteurs ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // server/ouvrage/_set_auteurs
       {
         String newAuteurs = in.read_string ();
         this.auteurs (newAuteurs);
         out = $rh.createReply();
         break;
       }

       case 3:  // server/ouvrage/_get_mots_clefs
       {
         String $result[] = null;
         $result = this.mots_clefs ();
         out = $rh.createReply();
         server.liste_stringHelper.write (out, $result);
         break;
       }

       case 4:  // server/ouvrage/_set_mots_clefs
       {
         String newMots_clefs[] = server.liste_stringHelper.read (in);
         this.mots_clefs (newMots_clefs);
         out = $rh.createReply();
         break;
       }

       case 5:  // server/ouvrage/_get_famille_ouvrage
       {
         server.famille $result = null;
         $result = this.famille_ouvrage ();
         out = $rh.createReply();
         server.familleHelper.write (out, $result);
         break;
       }

       case 6:  // server/ouvrage/_set_famille_ouvrage
       {
         server.famille newFamille_ouvrage = server.familleHelper.read (in);
         this.famille_ouvrage (newFamille_ouvrage);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:server/ouvrage:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ouvrage _this() 
  {
    return ouvrageHelper.narrow(
    super._this_object());
  }

  public ouvrage _this(org.omg.CORBA.ORB orb) 
  {
    return ouvrageHelper.narrow(
    super._this_object(orb));
  }


} // class ouvragePOA
