package servercompte;


/**
* servercompte/_allocateurStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from servercompte.idl
* lundi 15 janvier 2018 19 h 17 WET
*/

public class _allocateurStub extends org.omg.CORBA.portable.ObjectImpl implements servercompte.allocateur
{

  public void nouveau_compte (servercompte.compteHolder cpt, String titulaire, int numero_compte)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("nouveau_compte", true);
                servercompte.compteHelper.write ($out, cpt.value);
                $out.write_string (titulaire);
                $out.write_long (numero_compte);
                $in = _invoke ($out);
                cpt.value = servercompte.compteHelper.read ($in);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                nouveau_compte (cpt, titulaire, numero_compte        );
            } finally {
                _releaseReply ($in);
            }
  } // nouveau_compte

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:servercompte/allocateur:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _allocateurStub
