package servercompte;


/**
* servercompte/allocateur.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from servercompte.idl
* lundi 15 janvier 2018 19 h 17 WET
*/

public interface allocateur extends allocateurOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface allocateur
