package servercompte;


/**
* servercompte/allocateurPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from servercompte.idl
* lundi 15 janvier 2018 19 h 17 WET
*/

public abstract class allocateurPOA extends org.omg.PortableServer.Servant
 implements servercompte.allocateurOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("nouveau_compte", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // servercompte/allocateur/nouveau_compte
       {
         servercompte.compteHolder cpt = new servercompte.compteHolder ();
         cpt.value = servercompte.compteHelper.read (in);
         String titulaire = in.read_string ();
         int numero_compte = in.read_long ();
         this.nouveau_compte (cpt, titulaire, numero_compte);
         out = $rh.createReply();
         servercompte.compteHelper.write (out, cpt.value);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:servercompte/allocateur:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public allocateur _this() 
  {
    return allocateurHelper.narrow(
    super._this_object());
  }

  public allocateur _this(org.omg.CORBA.ORB orb) 
  {
    return allocateurHelper.narrow(
    super._this_object(orb));
  }


} // class allocateurPOA
