package servercompte;


/**
* servercompte/allocateurOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from servercompte.idl
* lundi 15 janvier 2018 19 h 17 WET
*/

public interface allocateurOperations 
{
  void nouveau_compte (servercompte.compteHolder cpt, String titulaire, int numero_compte);
} // interface allocateurOperations
