package servercompte;


/**
* servercompte/compteHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from servercompte.idl
* lundi 15 janvier 2018 19 h 17 WET
*/

abstract public class compteHelper
{
  private static String  _id = "IDL:servercompte/compte:1.0";

  public static void insert (org.omg.CORBA.Any a, servercompte.compte that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static servercompte.compte extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (servercompte.compteHelper.id (), "compte");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static servercompte.compte read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_compteStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, servercompte.compte value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static servercompte.compte narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof servercompte.compte)
      return (servercompte.compte)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      servercompte._compteStub stub = new servercompte._compteStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static servercompte.compte unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof servercompte.compte)
      return (servercompte.compte)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      servercompte._compteStub stub = new servercompte._compteStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
