package servercompte;

/**
* servercompte/compteHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from servercompte.idl
* lundi 15 janvier 2018 19 h 17 WET
*/

public final class compteHolder implements org.omg.CORBA.portable.Streamable
{
  public servercompte.compte value = null;

  public compteHolder ()
  {
  }

  public compteHolder (servercompte.compte initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = servercompte.compteHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    servercompte.compteHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return servercompte.compteHelper.type ();
  }

}
