package servercompte;


/**
* servercompte/compteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from servercompte.idl
* lundi 15 janvier 2018 19 h 17 WET
*/

public interface compteOperations 
{
  int numero_compte ();
  String titulaire ();
  double solde ();
  void nombre_operations (org.omg.CORBA.IntHolder nombre);
  void debiter (double montant);
  void crediter (double montant);
  void prelevement (double montant, servercompte.compte destination);
} // interface compteOperations
