package server.exo2;


/**
* server/exo2/calculOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* lundi 15 janvier 2018 17 h 57 WET
*/

public interface calculOperations 
{
  double memoire ();
  void ajouteMemoire (double donnee);
  void soustraitMemoire (double donnee);
  void multiplieMemoire (double donnee);
  void miseAZero ();
  void diviseMemoire (double donnee) throws server.exo2.divisionParZero;
  void incrementer (org.omg.CORBA.IntHolder data);
  void decrementer (org.omg.CORBA.IntHolder data);
} // interface calculOperations
