package server.exo2;


/**
* server/exo2/divisionParZero.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* lundi 15 janvier 2018 17 h 57 WET
*/

public final class divisionParZero extends org.omg.CORBA.UserException
{

  public divisionParZero ()
  {
    super(divisionParZeroHelper.id());
  } // ctor


  public divisionParZero (String $reason)
  {
    super(divisionParZeroHelper.id() + "  " + $reason);
  } // ctor

} // class divisionParZero
