package server;


/**
* server/_usineStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* lundi 12 février 2018 08 h 36 WET
*/

public class _usineStub extends org.omg.CORBA.portable.ObjectImpl implements server.usine
{

  public server.etudiant inscription_d_un_etudiant (String nom, String prenom)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("inscription_d_un_etudiant", true);
                $out.write_string (nom);
                $out.write_string (prenom);
                $in = _invoke ($out);
                server.etudiant $result = server.etudiantHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return inscription_d_un_etudiant (nom, prenom        );
            } finally {
                _releaseReply ($in);
            }
  } // inscription_d_un_etudiant

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:server/usine:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _usineStub
