package server;


/**
* server/etudiantHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* lundi 12 février 2018 08 h 36 WET
*/

abstract public class etudiantHelper
{
  private static String  _id = "IDL:server/etudiant:1.0";

  public static void insert (org.omg.CORBA.Any a, server.etudiant that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static server.etudiant extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (server.etudiantHelper.id (), "etudiant");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static server.etudiant read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_etudiantStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, server.etudiant value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static server.etudiant narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof server.etudiant)
      return (server.etudiant)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      server._etudiantStub stub = new server._etudiantStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static server.etudiant unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof server.etudiant)
      return (server.etudiant)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      server._etudiantStub stub = new server._etudiantStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
