package server;


/**
* server/etudiantOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* lundi 12 février 2018 08 h 36 WET
*/

public interface etudiantOperations 
{
  String nom ();
  String prenom ();
} // interface etudiantOperations
