package server;


/**
* server/usineOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* lundi 12 février 2018 08 h 36 WET
*/

public interface usineOperations 
{
  server.etudiant inscription_d_un_etudiant (String nom, String prenom);
} // interface usineOperations
