package server;


/**
* server/usine.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* lundi 12 février 2018 08 h 36 WET
*/

public interface usine extends usineOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface usine
