package server;

/**
* server/abonneHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* mercredi 24 janvier 2018 18 h 17 WET
*/

public final class abonneHolder implements org.omg.CORBA.portable.Streamable
{
  public server.abonne value = null;

  public abonneHolder ()
  {
  }

  public abonneHolder (server.abonne initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = server.abonneHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    server.abonneHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return server.abonneHelper.type ();
  }

}
