package server;


/**
* server/abonneOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* mercredi 24 janvier 2018 18 h 17 WET
*/

public interface abonneOperations 
{
  int numero ();
  String nom_prenom ();
  server.type_abonnement abonnement ();
  void abonnement (server.type_abonnement newAbonnement);
  server.type_adresse adresse ();
  void adresse (server.type_adresse newAdresse);
} // interface abonneOperations
