package server;


/**
* server/dejaExistant.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* mercredi 24 janvier 2018 18 h 17 WET
*/

public final class dejaExistant extends org.omg.CORBA.UserException
{

  public dejaExistant ()
  {
    super(dejaExistantHelper.id());
  } // ctor


  public dejaExistant (String $reason)
  {
    super(dejaExistantHelper.id() + "  " + $reason);
  } // ctor

} // class dejaExistant
