package server;


/**
* server/gestionabonnesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* mercredi 24 janvier 2018 18 h 17 WET
*/

public interface gestionabonnesOperations 
{
  server.abonne[] liste_abonnes ();
  void creation_abonne (int numero, String nom, String prenom, server.type_adresse adresse, server.type_abonnement abonnement, server.abonneHolder ref) throws server.dejaExistant;
  void resilier_abonne (int numero) throws server.numeroInconnu;
  void rechercher_abonne (int numero, server.abonneHolder ref) throws server.numeroInconnu;
} // interface gestionabonnesOperations
