package server;


/**
* server/table_abonneHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* mercredi 24 janvier 2018 18 h 17 WET
*/

abstract public class table_abonneHelper
{
  private static String  _id = "IDL:server/table_abonne:1.0";

  public static void insert (org.omg.CORBA.Any a, server.abonne[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static server.abonne[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = server.abonneHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (server.table_abonneHelper.id (), "table_abonne", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static server.abonne[] read (org.omg.CORBA.portable.InputStream istream)
  {
    server.abonne value[] = null;
    int _len0 = istream.read_long ();
    value = new server.abonne[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = server.abonneHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, server.abonne[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      server.abonneHelper.write (ostream, value[_i0]);
  }

}
