package server;

/**
* server/type_abonnementHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* mercredi 24 janvier 2018 18 h 17 WET
*/

public final class type_abonnementHolder implements org.omg.CORBA.portable.Streamable
{
  public server.type_abonnement value = null;

  public type_abonnementHolder ()
  {
  }

  public type_abonnementHolder (server.type_abonnement initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = server.type_abonnementHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    server.type_abonnementHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return server.type_abonnementHelper.type ();
  }

}
