package server;

/**
* server/type_adresseHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* mercredi 24 janvier 2018 18 h 17 WET
*/

public final class type_adresseHolder implements org.omg.CORBA.portable.Streamable
{
  public server.type_adresse value = null;

  public type_adresseHolder ()
  {
  }

  public type_adresseHolder (server.type_adresse initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = server.type_adresseHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    server.type_adresseHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return server.type_adresseHelper.type ();
  }

}
