package server;


/**
* server/type_adresse.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* mercredi 24 janvier 2018 18 h 17 WET
*/

public final class type_adresse implements org.omg.CORBA.portable.IDLEntity
{
  public int numero = (int)0;
  public String rue = null;
  public int code_postal = (int)0;
  public String ville = null;

  public type_adresse ()
  {
  } // ctor

  public type_adresse (int _numero, String _rue, int _code_postal, String _ville)
  {
    numero = _numero;
    rue = _rue;
    code_postal = _code_postal;
    ville = _ville;
  } // ctor

} // class type_adresse
