package server;


/**
* server/type_abonnementHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* mercredi 24 janvier 2018 18 h 17 WET
*/

abstract public class type_abonnementHelper
{
  private static String  _id = "IDL:server/type_abonnement:1.0";

  public static void insert (org.omg.CORBA.Any a, server.type_abonnement that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static server.type_abonnement extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (server.type_abonnementHelper.id (), "type_abonnement", new String[] { "forfait", "consommation"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static server.type_abonnement read (org.omg.CORBA.portable.InputStream istream)
  {
    return server.type_abonnement.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, server.type_abonnement value)
  {
    ostream.write_long (value.value ());
  }

}
