package server;


/**
* server/type_abonnement.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* mercredi 24 janvier 2018 18 h 17 WET
*/

public class type_abonnement implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static server.type_abonnement[] __array = new server.type_abonnement [__size];

  public static final int _forfait = 0;
  public static final server.type_abonnement forfait = new server.type_abonnement(_forfait);
  public static final int _consommation = 1;
  public static final server.type_abonnement consommation = new server.type_abonnement(_consommation);

  public int value ()
  {
    return __value;
  }

  public static server.type_abonnement from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected type_abonnement (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class type_abonnement
